services:
  - type: web
    name: trpc-websockets
    env: node
    plan: free
    buildCommand: yarn --prod=false &&
      yarn build
    startCommand: yarn start
    healthCheckPath: /api/trpc/healthz
    envVars:
      - key: NODE_ENV
        value: production

      - key: DATABASE_URL
        fromDatabase:
          name: quizr-db
          property: connectionString

      - fromGroup: quizr-main

databases:
  - name:quizr-db
    plan: free
